#################
### AUTOSTART ###
#################

exec-once = waybar &
exec-once = hyprpaper &
exec-once = hypridle &
exec-once = dunst &
exec-once = tailscale-systray &
exec-once = ~/.config/wallpapers/randomwallpaper.sh &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# GTK Theme
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"

# Matugen - Dynamic Theming
# We now trigger matugen explicitly in the wallpaper scripts for immediate updates.
