source = ~/.config/hypr/hyprlock_colors.conf

# [General]
ignore_empty_input = true

background {
    monitor =
    path = ~/.config/wallpapers/wallpaper
    new_optimizations=true
    noise = 0.081
    blur_passes = 3
    blur_size = 16
    blur_vibrancy = 0.1
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.2) # no fill

    outer_color = -1
    check_color = $primary
    fail_color= $error 
    capslock_color = $secondary

    fade_on_empty = false
    rounding = 5

    position = 0, -70
    halign = center
    valign = center

    font_family = Martian Mono Nerd Font 
    font_color = $text
    placeholder_text="°º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°º¤ø,¸"
}

# TIME
label {
    monitor =
    text = $TIME
    color = $text
    font_size = 144 
    font_family = Martian Mono Nerd Font
    position = 0, 180
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = $text
    font_size = 30 
    font_family = Martian Mono Nerd Font
    position = 0, 40
    halign = center
    valign = center
}

# WEATHER & NETWORK
label {
    monitor =
    text = cmd[update:3600000] echo "$(curl -s 'wttr.in/Vancouver?format=%c+%C+%t') | $(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d: -f2 || echo 'Disconnected')"
    color = $text
    font_size = 14
    font_family = Martian Mono Nerd Font
    position = 0, -100
    halign = center
    valign = top
}

# SONG
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/what_song.sh
    color = $text
    font_size = 14
    font_family = Martian Mono Nerd Font
    position = 0, 50
    halign = center
    valign = bottom
}
