# #######################################################################################
# HYPRLAND CONFIGURATION
# Modularized for 2026 Standards
# #######################################################################################

# Source modular config files
source = ~/.config/hypr/configs/colors.conf
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/execs.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/look.conf
source = ~/.config/hypr/configs/rules.conf
source = ~/.config/hypr/configs/keybinds.conf
